name: FrontPR Scan

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run FrontPR Scanner
        uses: carl773/FrontPR/github-action@017177b2b9d38ad9dc4319a4bb3b269a8a0498b2 # main
        with:
          target_url: https://brave-pond-0eeb5f910.7.azurestaticapps.net
          api_key: ${{ secrets.FRONTPR_API_KEY }}
